"""Advanced BEC AI Threat Detector using sentence-transformers embeddings.

This module trains a logistic regression classifier on sentence embeddings to
identify business email compromise (BEC) attempts that may be generated by
advanced AI systems. The example uses a small synthetic dataset but can be
extended with real-world BEC messages.
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer

DATA_PATH = "sample_bec_emails.csv"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"


def train_model(csv_path: str = DATA_PATH):
    """Train a BEC classifier using sentence embeddings."""
    data = pd.read_csv(csv_path)
    X_train, X_test, y_train, y_test = train_test_split(
        data["text"], data["label"], test_size=0.2, random_state=42
    )

    encoder = SentenceTransformer(EMBEDDING_MODEL)
    X_train_emb = encoder.encode(X_train.tolist(), convert_to_tensor=False)
    X_test_emb = encoder.encode(X_test.tolist(), convert_to_tensor=False)

    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train_emb, y_train)
    accuracy = clf.score(X_test_emb, y_test)
    print(f"BEC model trained. Test accuracy: {accuracy:.2f}")
    return encoder, clf


if __name__ == "__main__":
    encoder, clf = train_model()
    while True:
        text = input("Enter email text (or 'quit'): ")
        if text.lower() == "quit":
            break
        emb = encoder.encode([text], convert_to_tensor=False)
        prediction = clf.predict(emb)[0]
        print(f"Prediction: {prediction}\n")
